test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: meme_test

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: meme_development

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  url: <%= ENV["DATABASE_URL"] %>
